spigotIdeaGenerator:
   snippets: [
      "BASE:Whenever a %PERSON(A)% %ACTIONS%, they %ACTION_FORCED%.",
      "BASE:Whenever a %PERSON(A)% %ACTIONS%, a %PERSON(A)% %ACTIONS_FORCED%.",
      "BASE:Whenever a %PERSON(A)% %ACTIONS%, %THING% %ACTIONS_FORCED%.",
      "BASE:Every %DURATION%, a %PERSON(A)% %ACTIONS_FORCED%.",
      "BASE:Every %DURATION%, the %PERSON(THE)% %ACTIONS_FORCED%.",
      "BASE:Every %DURATION%, %THING% %ACTIONS_FORCED%.",
      "BASE:The %PERSON(THE)% that %CONDITION% %ACTIONS_FORCED%.",
      
      "ACTIONS:eats %THING%",
      "ACTIONS:places %THING%",
      "ACTIONS:places %THING% in %PLACE(IN)%",
      "ACTIONS:steps in/on %THING%",
      "ACTIONS:jumps",
      "ACTIONS:sneaks",
      "ACTIONS:falls in/on %THING%",
      "ACTIONS:heals",
      "ACTIONS:takes damage",
      "ACTIONS:hurts another player",
      "ACTIONS:%ACTIONS% in %PLACE(IN)%",
      "ACTIONS:%ACTIONS% at %PLACE(AT)%",
      "ACTIONS:%ACTIONS% or %ACTIONS%",
      "ACTIONS:breaks %THING%",
      "ACTIONS:goes to %PLACE(TO)%",
      "ACTIONS:dies",
      "ACTIONS:breaks",
      "ACTIONS:spawns %THING%",
      
      "ACTIONS_FORCED:dies",
      "ACTIONS_FORCED:is teleported to %PLACE(TO)%",
      "ACTIONS_FORCED:explodes",
      "ACTIONS_FORCED:spawns",
      "ACTIONS_FORCED:is healed",
      "ACTIONS_FORCED:gets some %THING(PL)%",
      "ACTIONS_FORCED:gets %THING%",
      "ACTIONS_FORCED:takes damage",
      "ACTIONS_FORCED:loses all their %POSSESION%",
      "ACTIONS_FORCED:has their %POSSESION% %CHANGED%",
      
      "ACTION_FORCED:die",
      "ACTION_FORCED:are teleported to %PLACE(TO)%",
      "ACTION_FORCED:explode",
      "ACTION_FORCED:spawn",
      "ACTION_FORCED:are healed",
      "ACTION_FORCED:get some %THING(PL)%",
      "ACTION_FORCED:get %THING%",
      "ACTION_FORCED:take damage",
      
      "PERSON(THE):host",
      "PERSON(THE):team",
      "PERSON(THE):player",
      "PERSON(A):team",
      "PERSON(A):player",
      "PERSON(A):player in your team",
      "PERSON(A):random player",
      
      "POSSESION:health",
      "POSSESION:xp",
      "POSSESION:hunger",
      "POSSESION:armor durability",
      "POSSESION:tool durability",
      "POSSESION:items",
      "POSSESION:healing",
      "POSSESION:enchantments",
      
      "THING:a block",
      "THING:an item",
      "THING:a random block",
      "THING:a random item",
      "THING:a mob",
      "THING:a random mob",
      "THING:armor",
      "THING:random armor",
      "THING:leather",
      "THING:sugar cane",
      "THING:a book",
      "THING:an enchanted book",
      "THING:an enchantment table",
      "THING(PL):ores",
      "THING(PL):trees",
      "THING:an animal",
      "THING(PL):animals",
      "THING:a gravity-affected block",
      "THING(PL):gravity-affected blocks",
      "THING:a diamond",
      "THING(PL):diamonds",
      "THING:iron",
      "THING:stone",
      "THING:coal",
      "THING:redstone",
      "THING:water",
      "THING:obsidian",
      "THING:lava",
      "THING:TNT",
      "THING:gold",
      "THING(PL):iron",
      "THING(PL):stone",
      "THING(PL):coal",
      "THING(PL):redstone",
      "THING(PL):water",
      "THING(PL):obsidian",
      "THING(PL):lava",
      "THING(PL):TNT",
      "THING(PL):gold",
      "THING(PL):golden apples",
      
      "DURATION:5 minutes",
      "DURATION:minute",
      "DURATION:30s-60s",
      "DURATION:10s",
      
      "CHANGES:increases",
      "CHANGES:is randomized",
      "CHANGES:decreases",
      "CHANGES:inverts",
      "CHANGES:is doubled",
      "CHANGES:is halved",
      
      "CHANGED:increased",
      "CHANGED:randomized",
      "CHANGED:decreased",
      "CHANGED:inverted",
      "CHANGED:doubled",
      "CHANGED:halved",
      
      "PLACE(TO):0,0",
      "PLACE(TO):the border",
      "PLACE(TO):a random location",
      "PLACE(TO):the build limit",
      "PLACE(TO):bedrock level",
      "PLACE(TO):the %PERSON(THE)%'s location",
      "PLACE(TO):a %PERSON(A)%'s location",
      "PLACE(IN):a forest",
      "PLACE(IN):a cave",
      "PLACE(IN):the sky",
      "PLACE(IN):the ground",
      "PLACE(IN):a fight",
      "PLACE:the location of %THING%",
      "PLACE(AT):0,0",
      "PLACE(AT):the border",
      "PLACE(AT):bedrock level",
      "PLACE(AT):build height",
      
      "CONDITION:is closest to %PLACE(TO)%",
      "CONDITION:is furthest from %PLACE(TO)%",
      "CONDITION:has the most %THING(PL)%",
      "CONDITION:has the least %THING(PL)%",
      "CONDITION:is nearest to %PLACE(TO)%",
      "CONDITION:is furthest from %PLACE(TO)%",
      "CONDITION:is in %PLACE(IN)%",
      "CONDITION:is outside of %PLACE(IN)%",
      "CONDITION:%ACTIONS% the most",
      "CONDITION:%ACTIONS% the least"
   ]
